s5p6818: Disable it7260 touchscreen driver
which causes build failure with latest gcc-11 and CONFIG_FORTIFY_SOURCE:

In function 'memcpy',
    inlined from 'i2c_master_write_it7260' at drivers/input/touchscreen/it7260_mts.c:94:2,
    inlined from 'it7260_ts_suspend' at drivers/input/touchscreen/it7260_mts.c:383:30:
./include/linux/string.h:341:25: error: call to '__write_overflow' declared with attribute error: detected write beyond size of object passed as 1st parameter
  341 |                         __write_overflow();
      |                         ^~~~~~~~~~~~~~~~~~

Signed-off-by: MichaIng <micha@dietpi.com>